// Regenerates src/lib/logos.ts from the SVG files in public/logos.
//
//   node scripts/generate-logos.mjs
//
// Run this after adding, replacing or removing a logo file. Inlining the SVGs
// means no network requests, no referrer leakage, no link rot, and — unlike an
// <img> — the marks can be recoloured and filtered per theme.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const LOGO_DIR = join(root, "public", "logos");
const OUT = join(root, "src", "lib", "logos.ts");

/** Marks wider than this render at fixed height with auto width. */
const WIDE_RATIO = 1.35;

const clean = (svg, key) => {
  let out = svg
    .replace(/<\?xml.*?\?>/gs, "")
    .replace(/<!--.*?-->/gs, "")
    .replace(/<title>.*?<\/title>/gis, "");

  // Some marks (Calendly, Vite) colour their paths through an internal <style>
  // block rather than fill attributes. Two things have to happen for those to
  // survive inlining:
  //
  //   1. Keep the class attributes. Stripping them leaves the paths unfilled,
  //      which renders as solid black.
  //   2. Namespace the class names. `.st0` is generic enough that two inlined
  //      logos would fight over it in the global stylesheet.
  const classNames = new Set(
    [...out.matchAll(/class="([^"]+)"/g)].flatMap((m) => m[1].split(/\s+/))
  );
  for (const cls of classNames) {
    if (!cls) continue;
    const scoped = `lg-${key}-${cls}`;
    out = out
      .replace(new RegExp(`\\.${cls}(?=[\\s{,.:])`, "g"), `.${scoped}`)
      .replace(new RegExp(`class="${cls}"`, "g"), `class="${scoped}"`);
  }

  // ids can collide the same way (masks, gradients, clip paths)
  const ids = new Set([...out.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
  for (const id of ids) {
    const scoped = `lg-${key}-${id}`;
    out = out
      .replaceAll(`id="${id}"`, `id="${scoped}"`)
      .replaceAll(`url(#${id})`, `url(#${scoped})`)
      .replaceAll(`href="#${id}"`, `href="#${scoped}"`);
  }

  // strip sizing + a11y attributes from the ROOT tag only
  out = out.replace(/<svg\b[^>]*>/, (tag) =>
    tag
      .replace(/\s+(width|height)="[^"]*"/g, "")
      .replace(/\s+(aria-hidden|focusable|role)="[^"]*"/g, "")
      .replace("<svg", '<svg aria-hidden="true" focusable="false"')
  );

  return out.split(/\s+/).join(" ").trim();
};

const aspectOf = (svg) => {
  const m = svg.match(/viewBox="([^"]+)"/);
  if (!m) return 1;
  const [, , w, h] = m[1].trim().split(/[\s,]+/).map(Number);
  return h ? w / h : 1;
};

const files = (await readdir(LOGO_DIR)).filter(
  (f) => f.endsWith(".svg") && !f.startsWith("monogram-")
);

const entries = new Map();
for (const file of files.sort()) {
  const name = file.slice(0, -4);
  const base = name.replace(/-(light|dark)$/, "");
  const variant = name.endsWith("-light")
    ? "light"
    : name.endsWith("-dark")
      ? "dark"
      : "one";
  const raw = await readFile(join(LOGO_DIR, file), "utf8");
  const entry = entries.get(base) ?? { wide: aspectOf(raw) > WIDE_RATIO };
  entry[variant] = clean(raw, base);
  entries.set(base, entry);
}

const lines = [
  "// AUTO-GENERATED by scripts/generate-logos.mjs — do not edit by hand.",
  "// Run `node scripts/generate-logos.mjs` after changing public/logos.",
  "",
  "export type LogoArt = {",
  "  /** Wordmark-shaped marks (Tailwind, n8n, Cypress) render at fixed height",
  "   *  with auto width — squeezing them into a square makes them tiny. */",
  "  wide: boolean;",
  "} & ({ one: string } | { light: string; dark: string });",
  "",
  "export const LOGOS: Record<string, LogoArt> = {",
];

let wideCount = 0;
for (const [base, entry] of [...entries].sort()) {
  const wide = entry.wide;
  if (wide) wideCount++;
  const art =
    entry.one !== undefined
      ? `one: ${JSON.stringify(entry.one)}`
      : `light: ${JSON.stringify(entry.light)}, dark: ${JSON.stringify(entry.dark)}`;
  lines.push(`  ${JSON.stringify(base)}: { wide: ${wide}, ${art} },`);
}
lines.push("};", "", "export type LogoKey = keyof typeof LOGOS;", "");

await writeFile(OUT, lines.join("\n"), "utf8");
console.log(
  `src/lib/logos.ts — ${entries.size} logos, ${wideCount} wordmark-shaped`
);
